import { PrismaClient } from "@prisma/client";
import { slugify } from "../src/lib/slugify";

const prisma = new PrismaClient();

async function ensureUniqueSlug(base: string, excludeId: number): Promise<string> {
  let slug = base;
  let attempt = 2;
  while (true) {
    const existing = await prisma.video.findUnique({ where: { slug } });
    if (!existing || existing.id === excludeId) return slug;
    slug = `${base}-${attempt}`;
    attempt++;
  }
}

async function main() {
  const videos = await prisma.video.findMany();
  let renamed = 0;

  for (const video of videos) {
    const base = slugify(video.title);
    const prefix = `${base}-`;
    const looksAutoGenerated =
      video.slug.startsWith(prefix) &&
      /^[0-9a-z]{5,10}$/.test(video.slug.slice(prefix.length));

    if (!looksAutoGenerated) continue;

    const newSlug = await ensureUniqueSlug(base, video.id);
    if (newSlug === video.slug) continue;

    await prisma.video.update({ where: { id: video.id }, data: { slug: newSlug } });
    console.log(`${video.slug} -> ${newSlug}`);
    renamed++;
  }

  console.log(`Listo. ${renamed} video(s) renombrados.`);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
